name: sneaker_shopping_prokit
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.4
  nb_utils: ^4.4.10
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.2.0
  provider: ^6.0.5
  form_field_validator: ^1.1.0
  pinput:
  flutter_html: ^2.2.1
  flutter_screenutil: ^5.6.1
  flutter_rating_bar: ^4.0.1

  # Sneaker Shopping App
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1



  amplify_flutter: ^0.6.12
  amplify_api: ^0.6.12
  amplify_auth_cognito: ^0.6.12
  amplify_core: ^0.6.12

  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7


  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "images/sneakerShopping/ic_sneaker_logo.png"

flutter:
  uses-material-design: true

  assets:
   - images/sneakerShopping/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

